alias ae="source .venv/bin/activate"
alias ce="python3 -m venv .venv"
alias de=deactivate
alias c=clear
alias cat=rich
alias e='exit'
alias emacs="open -a emacs"
alias grep=ggrep
alias la="pls -a"
alias nv=nvim
alias ohmyzsh="nvim ~/.oh-my-zsh"
alias org="cd ~/Dropbox/org && open -a emacs ."
alias pip=pip3
alias py=python3
alias python=python3
alias sz="source ~/.zshrc"
alias zk="cd ~/Zettelkasten && nvim zettel/index.md"
alias zshrc="nvim ~/.zshrc"
alias ed="eatlocal download"
alias es="eatlocal submit"
alias er="eatlocal display"
alias eg="cd ~/code/pybites"
alias cve="python3 -m venv .venv"
alias aliases="nv ~/.oh-my-zsh/custom/aliases.zsh"
alias ls="exa --icons --color always"
alias ll="exa -l --icons --group-directories-first --color always"
alias la="exa -la --icons --group-directories-first --color always"
alias lss="pls --sort ext"
alias lg=lazygit
alias dm="python ~/background.py Default"
alias lm="python ~/background.py daytime"
alias ds="sh ~/data_science.sh"
